### ISSUE TITLE
Not effective enough (imo)

### ISSUE THREAD

**Issue by DanielRuf** [magespecialist/m2-MSP_Shield#4]
Compared to solutions like NinjaFirewall and modsecurity this plugin does not prevent many attacks (jsfuck, new elements, ...). Blacklists are not a great idea, a whitelist does make more sense.

**Comment by phoenix128** [comment]
Hello @DanielRuf ,
thank you for your feedback.

This plugin is capable of detecting jsfuck attacks and it is not based on blackslists.
I am not sure you correctly configured it. If you need assitance feel free to post something here.

This is more a PHP-IDS variation for Magento and it is not an alternative to other protection system like **modsecurity** or a WAF.

**Comment by DanielRuf** [comment]
Well for me https://github.com/magespecialist/m2-MSP_Shield/blob/master/Model/Detector/Xss.php is a blacklist check and only covers a few attack types (imo there are many more - some are very sophisticated).

**Comment by phoenix128** [comment]
I think what you are looking for is here `\MSP\Shield\Model\Detector\Language`.
If you also check `\MSP\Shield\Test\Unit\Model\IpsTest` at line 325 you will see a detection test specificately for a jsfuck.

**Comment by DanielRuf** [comment]
Yes I saw this. My list was just an example (I did something similar like jsfuck but for PHP ;-)).

> This is more a PHP-IDS variation for Magento and it is not an alternative to other protection system like modsecurity or a WAF.

I'm fine with this =) Thanks for the clarification.

**Comment by phoenix128** [comment]
You are welcome. Feel free to share any idea you would like to see here.
